# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy dependencies
COPY auth/requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy service code
COPY auth /app

# Expose port
EXPOSE 8000

# Command to run the auth service
CMD ["uvicorn", "auth.main:app", "--host", "0.0.0.0", "--port", "8000"]
