# Use the official Python image as the base
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Streamlit app's requirements to the container
COPY frontend/requirements.txt /app/requirements.txt

# Install Python dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the entire frontend directory to the container
COPY frontend /app

# Expose Streamlit's default port
EXPOSE 8501

# Set the Streamlit configuration to allow external access
ENV STREAMLIT_SERVER_HEADLESS=true \
    STREAMLIT_SERVER_PORT=8501 \
    STREAMLIT_SERVER_ENABLE_CORS=true \
    STREAMLIT_SERVER_ADDRESS=0.0.0.0

# Define the command to run the Streamlit app
CMD ["streamlit", "run", "app.py"]
