# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy dependencies
COPY task_manager/requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy service code
COPY task_manager /app

# Expose port
EXPOSE 8001

# Command to run the task manager service
CMD ["uvicorn", "task_manager.main:app", "--host", "0.0.0.0", "--port", "8001"]
